import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

const apiBase = String.fromEnvironment('API_BASE_URL', defaultValue: 'http://localhost:3000');
const labels = <String,String>{'title':'Название','context':'Контекст','need':'Потребность','users':'Пользователи','data':'Данные и материалы','constraints':'Ограничения','outcome':'Ожидаемый результат','success':'Критерии успеха','contact':'Контакт','format':'Формат взаимодействия'};
void main() => runApp(const MaterialApp(title:'Паспорт задачи',debugShowCheckedModeBanner:false,home:Home()));

class Home extends StatefulWidget { const Home({super.key}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home> {
  String role='Бизнес', profile='business-1', step='idea';
  bool busy=false; String? notice;
  Map<String,dynamic>? task; List<dynamic> tasks=[];
  final idea=TextEditingController();
  final fields={for(final key in labels.keys) key:TextEditingController()};
  final answers=<TextEditingController>[];
  @override void initState(){super.initState();loadTasks();}
  @override void dispose(){idea.dispose();for(final c in fields.values){c.dispose();}for(final c in answers){c.dispose();}super.dispose();}
  Future<dynamic> api(String method,String path,[Object? body]) async {
    final uri=Uri.parse('$apiBase$path'); final headers={'Content-Type':'application/json'};
    final http.Response r=switch(method){'GET'=>await http.get(uri),'POST'=>await http.post(uri,headers:headers,body:jsonEncode(body??{})),_=>await http.put(uri,headers:headers,body:jsonEncode(body??{}))};
    final data=jsonDecode(utf8.decode(r.bodyBytes)); if(r.statusCode>=400) throw Exception(data['error']??'Ошибка запроса'); return data;
  }
  Future<void> run(Future<void> Function() fn) async {setState((){busy=true;notice=null;});try{await fn();}catch(e){if(mounted)setState(()=>notice=e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>busy=false);}}
  Future<void> loadTasks() async {try{final data=await api('GET','/api/tasks?owner=$profile');if(mounted)setState(()=>tasks=data);}catch(_){if(mounted)setState(()=>notice='Запустите API на порту 3000.');}}
  void fill(Map<String,dynamic> values){for(final key in labels.keys){fields[key]!.text=(values[key]??'').toString();}}
  Future<void> create() => run(() async {task=await api('POST','/api/tasks',{'owner':profile,'idea':idea.text});final result=await api('POST','/api/tasks/${task!['id']}/questions');task=result['task'];answers.clear();for(final _ in task!['questions']){answers.add(TextEditingController());}fill(Map<String,dynamic>.from(task!['fields']));setState((){step='questions';notice=result['notice'];});await loadTasks();});
  Future<bool> save() async {bool ok=true;await run(() async {task=await api('PUT','/api/tasks/${task!['id']}',{'owner':profile,'fields':{for(final key in labels.keys)key:fields[key]!.text},'answers':answers.map((c)=>c.text).toList()});setState(()=>notice='Черновик сохранён');await loadTasks();});if(notice!='Черновик сохранён')ok=false;return ok;}
  Future<void> publish() => run(() async {task=await api('POST','/api/tasks/${task!['id']}/publish',{'owner':profile,'confirm':true});setState((){step='done';notice='Задача опубликована';});await loadTasks();});
  void open(Map<String,dynamic> item){task=item;idea.text=item['idea']??'';fill(Map<String,dynamic>.from(item['fields']));answers.clear();for(final a in item['answers']){answers.add(TextEditingController(text:a));}setState(()=>step=item['status']=='published'?'done':'card');}
  Widget panel(Widget child)=>Card(color:Colors.white,elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)),child:Padding(padding:const EdgeInsets.all(24),child:child));
  @override Widget build(BuildContext context){final narrow=MediaQuery.sizeOf(context).width<800;return Theme(data:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF2B4CDA)),scaffoldBackgroundColor:const Color(0xFFF4F6FB),useMaterial3:true,inputDecorationTheme:const InputDecorationTheme(border:OutlineInputBorder(),filled:true,fillColor:Colors.white)),child:Scaffold(appBar:AppBar(backgroundColor:Colors.white,title:const Text('Паспорт задачи'),actions:[Padding(padding:const EdgeInsets.only(right:12),child:SegmentedButton<String>(segments:const [ButtonSegment(value:'Бизнес',label:Text('Бизнес')),ButtonSegment(value:'Команда',label:Text('Команда'))],selected:{role},onSelectionChanged:(v)=>setState((){role=v.first;step='idea';}))) ]),body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1180),child:Padding(padding:const EdgeInsets.all(20),child:narrow?ListView(children:[mainPanel(),const SizedBox(height:16),sidePanel()]):Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:7,child:SingleChildScrollView(child:mainPanel())),const SizedBox(width:20),Expanded(flex:3,child:SingleChildScrollView(child:sidePanel()))]))))));}
  Widget mainPanel(){if(role=='Команда')return panel(const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Для команд',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),SizedBox(height:12),Text('Каталог и отклики появятся на следующем этапе.') ]));return panel(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Создать задачу',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(step=='idea'?'Опишите идею, ответьте на вопросы и подтвердите карточку.':step=='questions'?'Ответьте на вопросы и заполните карточку.':step=='card'?'Проверьте факты перед публикацией.':'Карточка опубликована.'),const SizedBox(height:20),if(notice!=null)...[Container(width:double.infinity,padding:const EdgeInsets.all(12),color:const Color(0xFFEAF0FF),child:Text(notice!)),const SizedBox(height:16)],if(step=='idea')...[TextField(controller:idea,maxLines:5,decoration:const InputDecoration(labelText:'Коротко опишите задачу',hintText:'Например: хотим бота для ответов на вопросы клиентов')),const SizedBox(height:16),FilledButton(onPressed:busy?null:create,child:Text(busy?'Подождите…':'Создать черновик и получить вопросы'))],if(step=='questions')...[for(var i=0;i<(task?['questions'] as List).length;i++)...[Text('${i+1}. ${task!['questions'][i]}',style:const TextStyle(fontWeight:FontWeight.w600)),const SizedBox(height:8),TextField(controller:answers[i],maxLines:2,decoration:const InputDecoration(hintText:'Ваш ответ')),const SizedBox(height:18)],FilledButton(onPressed:()=>setState(()=>step='card'),child:const Text('Перейти к карточке'))],if(step=='card')...[for(final entry in labels.entries)...[TextField(controller:fields[entry.key],maxLines:entry.key=='title'?1:2,decoration:InputDecoration(labelText:entry.value)),const SizedBox(height:14)],Wrap(spacing:12,runSpacing:8,children:[OutlinedButton(onPressed:busy?null:save,child:const Text('Сохранить черновик')),FilledButton(onPressed:busy?null:() async {if(!await save()||!mounted)return;final confirmed=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Опубликовать задачу?'),content:const Text('Карточка станет видна командам только после вашего подтверждения.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Назад')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Подтвердить'))]));if(confirmed==true)await publish();},child:const Text('Опубликовать'))])],if(step=='done')...[const Icon(Icons.check_circle,color:Color(0xFF20805B),size:48),const SizedBox(height:12),Text((task?['fields']?['title']??'').toString(),style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('На следующем этапе здесь появятся рейтинг, каталог и отклики.'),const SizedBox(height:16),OutlinedButton(onPressed:()=>setState((){step='idea';idea.clear();}),child:const Text('Создать ещё задачу'))]]));}
  Widget sidePanel()=>panel(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Демо-профиль',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:profile,items:const [DropdownMenuItem(value:'business-1',child:Text('Компания 1')),DropdownMenuItem(value:'business-2',child:Text('Компания 2'))],onChanged:(v){if(v==null)return;setState((){profile=v;step='idea';});loadTasks();}),const SizedBox(height:24),const Text('Мои задачи',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:10),if(tasks.isEmpty)const Text('Пока нет задач'),for(final raw in tasks)ListTile(contentPadding:EdgeInsets.zero,title:Text((raw['fields']['title'] as String).isEmpty?raw['idea']:raw['fields']['title'],maxLines:2,overflow:TextOverflow.ellipsis),subtitle:Text(raw['status']=='published'?'Опубликована':'Черновик'),onTap:()=>open(Map<String,dynamic>.from(raw)))]));
}
